### ISSUE TITLE
Flex pages

### ISSUE THREAD

**Issue by acondura** [OleVik/grav-plugin-static-generator#11]
When trying to index search data through the UI I get this error in the logs:

Argument 1 passed to Grav\Plugin\StaticGenerator\Data\AbstractData::content() must be an instance of Grav\Common\Page\Page, instance of Grav\Common\Flex\Types\Pages\PageObject given, called in /var/www/webroot/ROOT/user/plugins/static-generator/classes/Data/SSEData.php on line 155

Does it mean this plugin doesn't support flex objects? I'm using this plugin with the latest 1.7 and Flex pages/users enabled.

Running the index/page command from the cli doesn't produce any index/static content either.

**Comment by acondura** [comment]
Changing Page to PageInterface in classes/Data/AbstractData::content() and in  classes/Data/DataInterface::content(), as well as adding 'use Grav\Common\Page\Interfaces\PageInterface;' at the top helps with index generation (bin/plugin static-generator index -cfw /route).

Generating the static page does work, yet.

**Comment by OleVik** [comment]
Until Flex Objects and 1.7 of Core are stable, I am not performing any compliance testing. There's just been to much mess with the path to 1.7 and changes to API, to make it worthwhile to branch and lock for that. Until 1.7 is stable, this plugin remains locked to 1.6.

**Comment by OleVik** [comment]
Solved in v[3.1.0](https://github.com/OleVik/grav-plugin-static-generator/releases/tag/3.1.0).
