### ISSUE TITLE
Plugin causes Grav 1.7 to crash due to blueprints.yaml

### ISSUE THREAD

**Issue by TheRealThor** [OleVik/grav-plugin-static-generator#13]
Upon installing the plugin using GPM on a fresh Grav 1.7 installation, the following error appeared in the browser calling the admin plugin: 

```

Exception: Trying to access array offset on value of type int
…/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php569

[..]
Arguments: 
"Trying to access array offset on value of type int"
"/Users/thor/Dev/www/grav/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php"
569
array:3 [▼
  "key" => 0
  "prefix" => "plugins.static-generator."
  "parent" => "plugins.static-generator.presets.*.links"
]

```

Looks like there is a parsing error of the plugins blueprints.yaml

**Comment by OleVik** [comment]
Which version of Grav, Admin, and Static Generator did you install? I get no errors with Grav v1.7.0-rc.14, Admin v1.10.0-rc.14, Static Generator 2.1.3.
