### ISSUE TITLE
404 on Docs URL in Plug-in info within Grav

### ISSUE THREAD

**Issue by Eihrister** [OleVik/grav-plugin-static-generator#17]
Hi!

![image](https://user-images.githubusercontent.com/5128823/120463165-ebe60680-c39b-11eb-86cd-9fe1f384ab52.png)

The "Docs" URL there 404's, should probably be updated to reflect its (new) location, currently points to (as the image shows):

https://github.com/OleVik/grav-plugin-static-generator/blob/develop/README.md

Kind regards,

Daniël

**Comment by OleVik** [comment]
I swear I fixed this twice before, but I guess that was other repos. Fixed in [3.1.1](https://github.com/OleVik/grav-plugin-static-generator/releases/tag/3.1.1).
